name: Student Management application

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18, 20]
    
    steps:
      - name: branch Checkout
        uses: actions/checkout@v4
        
      - name: nodeJs setup
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-cache-${{ matrix.node-version }}
      
      - run: npm install
      - run: npm test
      - run: npm run build
      
      - uses: actions/upload-artifact@v4
        with:
          name: report
          path: report.txt

  verify:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: report
            
      - run: cat report.txt